task:
  use_compute_credits: false
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  upgrade_script:
    - git fetch origin master
  pub_cache:
    folder: ~/.pub-cache
  matrix:
    - name: test
      test_script: flutter test
    - name: analyze
      script: flutter analyze
    - name: build
      script: flutter build apk -v --debug
      binaries_artifacts:
        path: "build/app/outputs/apk/debug/app-debug.apk"
    - name: build-apks+java-test+drive-examples
      create_device_script:
        echo no | avdmanager -v create avd -n test -k "system-images;android-21;default;armeabi-v7a"
      script:
        # Unsetting CIRRUS_CHANGE_MESSAGE and CIRRUS_COMMIT_MESSAGE as they
        # might include non-ASCII characters which makes Gradle crash.
        # See: https://github.com/flutter/flutter/issues/24935
        # This is a temporary workaround until we figure how to properly configure
        # a UTF8 locale on Cirrus (or until the Gradle bug is fixed).
        # TODO(amirh): Set the locale to UTF8.
        - echo "$CIRRUS_CHANGE_MESSAGE" > /tmp/cirrus_change_message.txt
        - echo "$CIRRUS_COMMIT_MESSAGE" > /tmp/cirrus_commit_message.txt
        - export CIRRUS_CHANGE_MESSAGE=""
        - export CIRRUS_COMMIT_MESSAGE=""
        - flutter test
        - flutter drive --target=test_driver/app.dart
        - export CIRRUS_CHANGE_MESSAGE=`cat /tmp/cirrus_change_message.txt`
        - export CIRRUS_COMMIT_MESSAGE=`cat /tmp/cirrus_commit_message.txt`

task:
  pub_cache:
    folder: ~/.pub-cache
  use_compute_credits: false
  osx_instance:
    image: mojave-xcode-10.2-flutter
  setup_script:
    - pod repo update
  create_simulator_script:
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-2 | xargs xcrun simctl boot
  matrix:
    - name: build-ipas+drive-examples
      env:
        PATH: $PATH:/usr/local/bin
      build_script:
        - flutter test
        - flutter drive --target=test_driver/app.dart