task:
  use_compute_credits: false
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  upgrade_script:
    - git fetch origin master
  pub_cache:
    folder: ~/.pub-cache
  matrix:
    - name: test
      test_script:
        - flutter packages get
        - flutter test
    - name: analyze
      script:
        - flutter packages get
        - flutter analyze
    - name: build
      script:
        - flutter packages get
        - flutter build apk -v --debug
      binaries_artifacts:
        path: "build/app/outputs/apk/debug/app-debug.apk"

task:
  pub_cache:
    folder: ~/.pub-cache
  use_compute_credits: false
  osx_instance:
    image: mojave-xcode-10.2-flutter
  setup_script:
    - pod repo update
  create_simulator_script:
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-2 | xargs xcrun simctl boot
  matrix:
    - name: build-ipas+drive-examples
      env:
        PATH: $PATH:/usr/local/bin
      build_script:
        - flutter packages get
        - flutter test
        - flutter drive --target=test_driver/app.dart